RENDERER_ADDRESS_BASE = "192.168.1."  # beaglexm
RENDERER_ADDRESS_BASE_OCTET = 101     # beaglexm0
#RENDERER_ADDRESS_BASE = "192.168.0."  # dweeno
#RENDERER_ADDRESS_BASE_OCTET = 113     # dweeno
#RENDERER_ADDRESS_BASE = "127.0.0."  # octets ending in a dot
#RENDERER_ADDRESS_BASE_OCTET = 1
RENDERER_PORT = 5001
RENDERER_CONNECT_TIMEOUT_SECS = 2.0
MAXIMUM_RENDERER_CONNECT_RETRIES = 10 
# We have 4 columns and 2 rows
#ZONES=[1,1]
ZONES=[4,2]
RENDERER_CONFIG_MAX_LENGTH = 512
